### ISSUE TITLE
2nd Release - M101.0.4921.0 - AVX2 is brocken

### ISSUE THREAD

**Issue by Lehner82** [Alex313031/Thorium-AVX2#1]
Both installer and portable. Error: RESULT_CODE_MISSING_DATA

**Comment by oka1q** [comment]
Use Compatibility Mode with win 7 or 8.

**Comment by Alex313031** [comment]
@Lehner82 @oka1q Yep! Known upstream bug.

**Comment by Alex313031** [comment]
@Lehner82 Checking back in before I close this issue, do you have it working now?
