### ISSUE TITLE
Window flashes and quits. Won't run

### ISSUE THREAD

**Issue by BigT2013** [Alex313031/Thorium-AVX2#107]
**System Details**
 - OS: [e.g.  Ubuntu 22.04, Windows 7, 8.1, 10, 11]
 - Thorium Version [e.g.107.0.5347.0]

**Problem**

**Screenshots**

**Additional Notes**

**Comment by gz83** [comment]
please try to use this version

https://github.com/Alex313031/Thorium-SSE3/releases/tag/M117.0.5938.157-1

**Comment by mi-molette** [comment]
works for me thx :)

**Comment by pomodori92** [comment]
@Alex313031 this issue is solved.
