### ISSUE TITLE
Please force-enable the Google Search dark mode option

### ISSUE THREAD

**Issue by Void48** [Alex313031/Thorium-AVX2#108]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I google something in Incognito mode and the google search blinds me because it defaults to light mode instead of dark mode. 

The default option Google Search uses when you search for something in Incognito mode is: **Device default**
But I would like it to use **Dark theme: on** always

**Describe the solution you'd like, including relevant patches or source**
Would love for Thorium to force the dark mode option to be enabled by default (the default Google Search one) when I search for something in Incognito mode

**Comment by yurikodesu** [comment]
That isn't Thorium's problem, that's intended as you need cookies to save the light/dark mode theme and it defaults to light because of the same.

**Comment by pomodori92** [comment]
@Void48 try using Stylish extension. You can set a theme for Google or other websites.
