### ISSUE TITLE
Thorium menu font size doesn't change.

### ISSUE THREAD

**Issue by pomodori92** [Alex313031/Thorium-AVX2#109]
**System Details**
 - OS: Windows 10 22H2
 - Thorium Version 117.0.5938.157 AVX2

**Problem**
Increasing the minimum and maximum font sizes has no effect on the font size within the Thorium menu.

**Screenshots**
![immagine](https://github.com/Alex313031/Thorium-Win-AVX2/assets/45762339/126ca324-14fa-4eac-ad48-2962a9b04e43)

**Additional Notes**

**Comment by gz83** [comment]
Please test whether the same is true for Chromium. If so, it means that this feature only takes effect on web pages.

**Comment by pomodori92** [comment]
You're right.
