### ISSUE TITLE
Some tabs on the right not rendered (but exist) upon starting the browser.

### ISSUE THREAD

**Issue by maxwowpow** [Alex313031/Thorium-AVX2#110]
**System Details**
 - OS: win 11
 - Thorium Version Avx2/117

**Problem**
- Reproducible 100% of the time. 
- e.g. 1 pinned tab, 6 collapsed groups, 1 expanded group.

- browser opened - some groups are shown (in the beginning), some "disappear"/invisible (in the end).
- the smaller the browser window width/size - more tabs/groups are striped/hidden from/on the right (only upon startup).

- tabs reappear after resizing of any kind (e.g. exiting full screen/max/min) and "rendering" triggers as **opening a new tab** / clicking other groups (expanding/collapsing).
- 2-3 Monitor setup.

**Screenshots**
E.g.: 1 pinned tab, 7 (!) tab groups. Last (7th group) expanded, but only "first two" visible. "+"-new tab button at the farther most right.
![Screenshot 2023-11-01 175655](https://github.com/Alex313031/Thorium-Win-AVX2/assets/169885/a9162949-9164-43bf-91cf-20d1a51baa01)

**Additional Notes**
- [pinned tabs issue](https://github.com/Alex313031/Thorium-Win-AVX2/issues/92)
- 2-3 Monitor setup, Nvidia, HW enabled.
- some size calc failure on start up to render tabs?

**Comment by gz83** [comment]
Does the same version of Chromium also have this problem? What experimental flags have you turned on?

**Comment by maxwowpow** [comment]
![Screenshot 2023-11-03 172926](https://github.com/Alex313031/Thorium-Win-AVX2/assets/169885/49abf59d-e1f5-4b36-a63a-9d92d4c6b954)

will check the chromium.

**Comment by Alex313031** [comment]
@maxwowpow Try latest M119 version, without any flags set.

**Comment by maxwowpow** [comment]
haven't been using groups for some time now. 
this could be tentatively closed and reopened if the problem persists. 
If it was some gpu driver glitch the issue would be left opened unnecessarily.

**Comment by Alex313031** [comment]
@maxwowpow OK. Feel free to re-open if necessary.
