### ISSUE TITLE
New Tab: empty with no shorcuts.

### ISSUE THREAD

**Issue by maxwowpow** [Alex313031/Thorium-AVX2#111]
**Is your feature request related to a problem? Please describe.**
Currently new tab has "shortcuts" from history. 

**Describe the solution you'd like, including relevant patches or source**
I'd like to have it empty.

**Additional Notes**
![Screenshot 2023-11-01 185233](https://github.com/Alex313031/Thorium-Win-AVX2/assets/169885/9aea0d1b-a306-4113-9382-5f922e7a26d8)

**Comment by gz83** [comment]
Open chrome://flags, find custom-ntp, and customize the NTP page there

**Comment by maxwowpow** [comment]
It's only a workaround, not a clean solution. In case of about:blank it's not "synchronized" with the overall color theme/design of the browser. `about:blank` would be possible w/o flags+NTP and setting NTP manually tweaked to a color scheme requires a separate webpage, picking a color and updating it when the accent color changes.
