### ISSUE TITLE
Crashes on the startup

### ISSUE THREAD

**Issue by hvlxh** [Alex313031/Thorium-AVX2#113]
**System Details**
 - OS: win 10
 - Thorium latest version of thorium win

**Problem**
When i start the app, it crashes few seconds later

**Screenshots**
https://github.com/Alex313031/Thorium-Win-AVX2/assets/91016099/977b060f-a5b2-4d36-a16f-9b6ad4fdb1a5

**Comment by gz83** [comment]
Please provide the processor model your computer is currently using

**Comment by hvlxh** [comment]
Intel Core i3-2120

**Comment by gz83** [comment]
You should use the version from the Thorium-SSE3 repo
