### ISSUE TITLE
Issue with Google Meet

### ISSUE THREAD

**Issue by x0rsw1tch** [Alex313031/Thorium-AVX2#114]
**System Details**
 - OS: Windows 11 x64 22621.2715
 - Thorium Version: 117.0.5938.157 (Official Build) (64-bit)
 - CPU: Ryzen 7900X
 - GPU: nvidia RTX 4090

**Problem**

I switched to Thorium recently, and have never encountered this problem before. Not sure why this is happening, maybe due to hardware acceleration, I haven't had the chance to test this? The screenshot pretty much sum up the problem.

**Screenshots**

![image](https://github.com/Alex313031/Thorium-Win-AVX2/assets/9543257/fbe36736-0fc9-4eb3-9c79-42b095157676)

**Additional Notes**

I noticed these behaviors as well:

- My camera always looks fine. Others, not so much
- If there is just one other camera active, that is also fine.
- Everyones cameras look fine when someone is doing a screenshare, and all of the attendees cameras are moved to the side. the screenshare itself also has no problems

**Comment by BSoD38** [comment]
I have the exact same issue. I have a RTX 2080 Super.

**Comment by Alex313031** [comment]
@x0rsw1tch @BSoD38 Can y'all try the new M119 version and see if it fixes your issues?

**Comment by franz-dc** [comment]
@Alex313031 Still happens on M119, although I am using the AVX build.
Tested it on i7 13700K + RTX 4080 if that helps.

**Comment by x0rsw1tch** [comment]
@Alex313031  Still happening for me as well, AVX2 build: Ryzen 7900X + RTX 4090

![image](https://github.com/Alex313031/Thorium-Win-AVX2/assets/9543257/a83cbc3f-b0eb-432c-9aab-23f5bb0b442b)

**Comment by w33bored** [comment]
Just confirming that I am having this issue as well. 
<img width="1537" alt="thorium1" src="https://github.com/Alex313031/Thorium-Win-AVX2/assets/157732754/30ed6b12-8bc4-4584-9870-d970895e31ee">
A few screens look okay.

Once we share our screen and put something up, it seems to fix the issues for the most part.

**Comment by ghost** [comment]
Same issue. 


Someone shared their screen and the weird artifacts stopped, but the videos seem very grainy and a little blurry. Hard to see with the censorship here. You can see it around their faces.

<img width="1537" alt="thorium1" src="https://github.com/Alex313031/Thorium-Win-AVX2/assets/157732754/33c76e13-a087-4b2e-a81f-be3826ad86bc">
<img width="772" alt="thorium2" src="https://github.com/Alex313031/Thorium-Win-AVX2/assets/157732754/aad40d42-add1-41c5-81c0-4f0d192c287b">
