### ISSUE TITLE
crashes using "search Settings"

### ISSUE THREAD

**Issue by blackweta** [Alex313031/Thorium-AVX2#12]
Loving the browser  - insanely fast on Speedometer 2 benchmark. I'm using Version 103.0.5014.0 (Official Build) (64-bit), when I use the settings search box I'm greeted with the browser crashing.  Also when navigating settings using the settings menu on the left. selecting Privacy & Security  (I think I dont want to check as I'm logging this in Thorium. crash dump attached.
[1754afc0-5857-4f74-a9d5-61e885cfa551.zip](https://github.com/Alex313031/Thorium-AVX2/files/8537992/1754afc0-5857-4f74-a9d5-61e885cfa551.zip)
 )

**Comment by Alex313031** [comment]
@blackweta I'm aware of this bug, only shows up on windows builds. Im investigating it. And thanks for the dump, but its actually not much use because as part of Thorium's compiler optimizations, it is built with no debugging symbols at all.
