### ISSUE TITLE
About politicization

### ISSUE THREAD

**Issue by Rusenche** [Alex313031/Thorium-AVX2#121]
`(Notably not in Russia or China because ya know, their governments being oppressive and stuff and not allowing certain URLs.`

I am absolutely disgusted by the politicization that had no place in software! This is posted here: https://github.com/Alex313031/Thorium-Win-AVX2/releases/tag/M119.0.6045.214/

With the same note of negation, I can claim that the `usa` is the aggressor and the `usa` is the enemy of humanity! And Joe Bidon is a dictator!

Please refrain from bringing propaganda into the software!

**Comment by Alex313031** [comment]
@Rusenche I mean..... they do block alot of western URLs. I will remove the "oppressive" since that is a matter of opinion and not fact.

If I were to have added the search engines for those locales, they wouldn't have worked anyway. (Unless you use a VPN to bypass content restrictions)
