### ISSUE TITLE
Group: Invalid DRM error with DRM_FAILED_LICENSE_REQUEST Code: 2003 NBA league pass game stream error

### ISSUE THREAD

**Issue by Rocman76** [Alex313031/Thorium-AVX2#123]
I can't play back NBA games from the leaguepass streaming service specifically, all other video is fine, error is:

Group: Invalid DRM error with DRM_FAILED_LICENSE_REQUEST
Code: 2003

Obviously a DRM issue but I can't find a way to fix it. It was also this way in the last release. Only Thorium has this issue and other browsers play the game streams fine.

**Comment by etil2jz** [comment]
See #84

**Comment by Alex313031** [comment]
@etil2jz @Rocman76 Yup. Its a widevine thing that I can't fix from my end without paying an amount of money that is not feasible for an open source project (and probably not feasible even in a closed-source project unless you are a larger company like Brave who can afford to get a widevine .sig)

**Comment by Rocman76** [comment]
@Alex313031 all good, as long as I know why I can work around it. Thanks for the reply.

**Comment by chaoscreater** [comment]
> @etil2jz @Rocman76 Yup. Its a widevine thing that I can't fix from my end without paying an amount of money that is not feasible for an open source project (and probably not feasible even in a closed-source project unless you are a larger company like Brave who can afford to get a widevine .sig)

But Quirk Player (https://github.com/Alex313031/quark-player) works fine?

**Comment by Alex313031** [comment]
@Rocman76  @chaoscreater Quark Player works fine because it uses CastLab's Electron fork, and they offer a free Widevine signing service. But it only works on their Electron.

**Comment by chaoscreater** [comment]
> @Rocman76 @chaoscreater Quark Player works fine because it uses CastLab's Electron fork, and they offer a free Widevine signing service. But it only works on their Electron.

Thanks and just out of curiosity, why does Brave browser work fine with Netflix? It's also Chromium based too. I'm guessing they paid the license to use widevine?

**Comment by Alex313031** [comment]
@chaoscreater Yes. You can easily tell if a browser is widevine signed because there is a .sig file named after the main binary, next to the main binary.

For example, chrome.sig, brave.sig, firefox.sig.

**Comment by chaoscreater** [comment]
Thanks man. That makes sense and I found brave.exe.sig in the folder.

I love Thorium too much to just give it up, so I'm gonna keep using it. In the meantime, there's a couple of workarounds for anyone else reading this:

- Use Quark Player

- Use Chrome or Firefox. You can easily install something like Open In Chromium from Chrome web store, then configure it to open netflix.com directly with Chrome:

![image](https://github.com/Alex313031/Thorium-Win-AVX2/assets/18227319/6461e811-5f7e-4730-b317-5efd24d41b55)

Make sure the binary to the exe is not enclosed in quotes. It has to be like what's shown in my screenshot. I'm not pointing it to Chrome but you get the idea.

- Use Netflix modern app from MS Store

**Comment by Alex313031** [comment]
@chaoscreater @Rocman76 @etil2jz @midzer @gz83 

I contacted Castlabs, SentryDRM, and widevine.org itself, and the LOWEST quote I got was $7,000 up front, plus a yearly licensing fee of $2,000 dollars.

Obviously, you can see why Brave, Firefox, Chrome, and Edge can afford this, while Thorium, Chromium, Ungoogled Chromium, and Iridium cannot.

Unless someone wants to donate such a large sum, I'm afraid you will have to use Quark Player or a mainstream browser.

However, Widevine still works on alot of sites (Like Hulu), so that's why I still include it. But I'm getting *really* tired of people not reading the discussions or checking the issues, and constantly posting issues like "why does streaming site xxxyyy not play in Thorium"......
