### ISSUE TITLE
Bug with user folder data (~dp0)

### ISSUE THREAD

**Issue by jestxfot** [Alex313031/Thorium-AVX2#124]
**System Details**
 - OS: [Windows 10]
 - Thorium Version [119]

**Problem**
The default folder is created in the `~dp0\USER DATA` directory, not the usual `USER_DATA` directory.

**Screenshots**
![image](https://github.com/Alex313031/Thorium-Win-AVX2/assets/87380272/ca26b83b-4eca-434c-b223-5a36b8615019)

**Additional Notes**
As a temporary measure you can remove these flags, most likely this flag was used for linux if I understand correctly, but it doesn't work in Windows

![image](https://github.com/Alex313031/Thorium-Win-AVX2/assets/87380272/d1c8d6a4-1a1f-42de-8e52-b30e7065a5d4)

**Comment by Alex313031** [comment]
@jestxfot You should leave the user-data-dir flag alone. It is the recently added cache flag that is the problem.

**Comment by jestxfot** [comment]
for win:
```
START "" "%cd%\BIN\thorium.exe" --user-data-dir="..\USER_DATA" --disk-cache-dir="..\..\USER_DATA\cache" --allow-outdated-plugins --disable-logging --disable-breakpad
```
