### ISSUE TITLE
Can't open Thorium 

### ISSUE THREAD

**Issue by jonathand-cf** [Alex313031/Thorium-AVX2#125]
**System Details**
 - OS: [Microsoft Windows 11 Pro, Version 10.0.22621, Build 22621]
 - Thorium Version [119.0.6045.214 (AVX2) ]
 - Processor [Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz, 2904 Mhz, 6 Core(s), 6 Logical Processor(s) (AVX2)]
 
**Problem**
I have AVX2 but still cant open Thorium, tried downloading earlier versions again, but that does not work anymore.
I had Thorium [117.0.5938.157] and that worked until i tried to update to 119, when it did not work anymore.

**Screenshots**
![image](https://github.com/Alex313031/Thorium-Win-AVX2/assets/56528814/ee46ee59-ae90-4b65-8ae5-1edba0c91426)

![image](https://github.com/Alex313031/Thorium-Win-AVX2/assets/56528814/2308baa3-3bab-42bc-b131-e744bf0b5037)

**Additional Notes**
This could be a one time issue for me, can you guys think of any solutions?
If you need any more system information i will provide in comments.

**Comment by jonathand-cf** [comment]
![image](https://github.com/Alex313031/Thorium-Win-AVX2/assets/56528814/77acc976-e615-4f9d-a6f0-817f5cd57c4a)
forgot this1

**Comment by gz83** [comment]
You need to run thorium.exe

**Comment by jonathand-cf** [comment]
i have, didnt think i needed to screenshot that

**Comment by jonathand-cf** [comment]
When i try to open the exe or for the sake of it the shortcut, the screen flashes with a white box and then it just does not execute.

**Comment by jonathand-cf** [comment]
https://github.com/Alex313031/Thorium-Win-AVX2/assets/56528814/db17c2d4-74b0-43af-8023-560e2eff89b1
