### ISSUE TITLE
Skylake laptop incompatible with portable install of Thorium AVX2 M119.0.6045.214 - 29th Release 

### ISSUE THREAD

**Issue by NTheZone** [Alex313031/Thorium-AVX2#128]
**System Details**
 - OS: Windows 10 Pro, 22H2, 64-bit, OS Build 19045.3930
 - Thorium Version: AVX2 M119.0.6045.214 - 29th Release 

**Problem**
Portable application does not start up, whether from cmd line or powershell using .BAT file from a partitioned drive.  Double-clicking on exe in BIN directory does nothing.

**Screenshots**
N.A.

**Additional Notes**
Processor: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz   2.40 GHz

**Comment by Alex313031** [comment]
@NTheZone Can you try the latest M121 version.

**Comment by NTheZone** [comment]
Hi Alex, both portable versions 120 and 121 AVX2 have worked fine on my Skylake laptop.  Thank you.
