### ISSUE TITLE
Download button randomly disappears 

### ISSUE THREAD

**Issue by regerohan** [Alex313031/Thorium-AVX2#129]
**System Details**
 - OS: Windows 11 Build 22631.3155
 - Thorium Version120.0.6099.235

**Problem**
The download button sometimes disappears from the menubar. The only way to get it back is to download something.

**Comment by gz83** [comment]
The logic of this feature is consistent with Chrome/Chromium, and you will observe the same behavior on Chrome/Chromium

@regerohan
