### ISSUE TITLE
Software crash while creating a new profile

### ISSUE THREAD

**Issue by fg-personal** [Alex313031/Thorium-AVX2#131]
**System Details**
 - OS: Windows 10
 - Thorium Version 121.0.6167.204 (Official Build) (64-bit)

**Problem**
Software crashes and closes when trying to create a new profile. The current profiles (profile 1 and guest) are working just fine.

**Additional Notes**
Crash report
[d3e4d19a-2b77-45e6-8914-e44c996bfeba.dmp](https://github.com/Alex313031/Thorium-Win-AVX2/files/14374353/d3e4d19a-2b77-45e6-8914-e44c996bfeba.dmp)

**Comment by gz83** [comment]
Duplicate issue, crash will be fixed in the next version, do not use this feature currently
