### ISSUE TITLE
Error on play video content from streaming services 

### ISSUE THREAD

**Issue by jhaveDK** [Alex313031/Thorium-AVX2#133]
Hello, 

I have problems with play content from Netflix and other video streaming services. Is there a fix  

**System Details**
 - OS: Windows 11 Pro
 - Thorium Version: 124.0.6367.218 (Officiel version) (64-bit)

**Screenshots**
https://i.imgur.com/lHvIeYt.jpeg

**Comment by gz83** [comment]
https://github.com/Alex313031/thorium/blob/main/docs/FAQ.md
