### ISSUE TITLE
2nd Release - M101.0.4921.0 - AVX2 Crashes

### ISSUE THREAD

**Issue by gz83** [Alex313031/Thorium-AVX2#2]
2nd Release - M101. 0.4921.0 - avx2 browser crashes after startup. It can only be used in compatibility mode. Please fix it.

**Comment by Alex313031** [comment]
@gz83 This is an upstream bug and I don't know how to fix it. Setting compatibility mode is easy to do, and fixes it. I will post a notice on the latest releases.

**Comment by gz83** [comment]
> @gz83 This is an upstream bug and I don't know how to fix it. Setting compatibility mode is easy to do, and fixes it. I will post a notice on the latest releases.

OK, I see. Thank you for your work.

**Comment by Alex313031** [comment]
@gz83 Yeah, wish I could tell you different. I'm not a super experienced Chromium dev, and oftentimes it takes all of my brain power to work on Thorium, so for issues that are upstream, I rarely know how to fix them. (Excluding one issue, which I actually fixed myself and made a bug report with the fix and it was merged for me by a higher up since I don't have commiter privileges.)

**Comment by gz83** [comment]
> @gz83 Yeah, wish I could tell you different. I'm not a super experienced Chromium dev, and oftentimes it takes all of my brain power to work on Thorium, so for issues that are upstream, I rarely know how to fix them. (Excluding one issue, which I actually fixed myself and made a bug report with the fix and it was merged for me by a higher up since I don't have commiter privileges.)

OK, I got it.

**Comment by Alex313031** [comment]
@gz83 Sorry didn't mean to annoy you. Also, should we close this issue, and defer to your other open issue for discussion?

**Comment by gz83** [comment]
> @gz83 Sorry didn't mean to annoy you. Also, should we close this issue, and defer to your other open issue for discussion?

I have now reverted to the old version for use, and have not encountered other problems for the time being. I will close this issue later.
