### ISSUE TITLE
Thorium Crashing On clicking "customize thorium" 

### ISSUE THREAD

**Issue by DexteR-mask** [Alex313031/Thorium-AVX2#23]
Thorium Crashing On clicking "customize thorium" 
14th Release - M106.0.5199.0
Win 11 64 bit
I3-11gen laptop
I would be happy to provide more info

**Comment by Alex313031** [comment]
@DexteR-mask Thiis is a known issue. I'm actually making a debug build today to see if i can find out what it is

**Comment by DexteR-mask** [comment]
ok But i have a question does building  on my pc ,will it lead to performance  boost or it is the same as building on others machines and running on different machines

**Comment by Alex313031** [comment]
@DexteR-mask Its the same, no matter what machine you compile it on, if you use the same compiler flags, you will get the exact same binary.

**Comment by Alex313031** [comment]
@DexteR-mask Issue has been fixed > https://github.com/Alex313031/Thorium-Win/releases/tag/M106.0.5219.0

**Comment by DexteR-mask** [comment]
The issue has been solved
