### ISSUE TITLE
Portable THORIUM.BAT fails to launch when there's a space in the path

### ISSUE THREAD

**Issue by Delphox** [Alex313031/Thorium-AVX2#25]
![image](https://user-images.githubusercontent.com/5883538/185295970-33dfcb94-64a5-40a3-9a23-99e11eb3c66f.png)

It's due to the `%cd%\BIN\thorium.exe` part not being quoted, but just quoting it breaks the command. 

I fixed it on my end by changing the start command to ``START "" "%cd%\BIN\thorium.exe"``
![image](https://user-images.githubusercontent.com/5883538/185296361-eb928048-0c7c-4cad-a7f4-878aaa84a6ed.png)

Unless I'm missing something I'm not sure what the original ``/D "%cd%\BIN\"`` is for, as the working directory never changes from where the bat is anyway. If it's for just to feed an argument to START so it launches Thorium without keeping a cmd window hostage, then just a "" is the standard for achieving that.

**Comment by Alex313031** [comment]
@Delphox Ok thanks, I will change this!

**Comment by Delphox** [comment]
I see! I was wondering if it had any other purpose. In this case I made a PR in the main repo. 😉
