### ISSUE TITLE
Google AdSense dashboard doesn't load

### ISSUE THREAD

**Issue by SodaPortal** [Alex313031/Thorium-AVX2#30]
![image](https://user-images.githubusercontent.com/37872928/186950515-ae838d92-6eda-45bd-97cd-7fbc8bafadce.png)
Works in Chrome 104, and justclueless/chromium-win64 [v107.0.5252.0-r0-AVX2](https://github.com/justclueless/chromium-win64/releases/tag/v107.0.5252.0-r0-AVX2)
Win 11, Ryzen 9 5950x
I tried clean reinstalling Thorium and using different DNS servers to ensure it wasn't a DNS issue.
I can provide more details if needed!

**Comment by lqdforce** [comment]
can confirm, AdSense doesn't load - as does Google Ads, Analytics and dashboards.
It does work fine on latest release of the non-AVX2 version (Thorium-Win M106.0.5237.0).

**Comment by SodaPortal** [comment]
Fixed in [M107.0.5271.0](https://github.com/Alex313031/Thorium-AVX2/releases/tag/M107.0.5271.0)

**Comment by lqdforce** [comment]
@SodaPortal any idea what was the fix? it seems the bug returned in 5314 . at least for me.

**Comment by SodaPortal** [comment]
@lqdforce this bug returned for me in 5314 as well.
