### ISSUE TITLE
GitHub settings page sidebar doesn't navigate

### ISSUE THREAD

**Issue by SodaPortal** [Alex313031/Thorium-AVX2#31]
When trying to click any of the buttons on the sidebar of the profile settings panel on github.com, does not navigate to other pages. No warnings were observed in the developer console.
![image](https://user-images.githubusercontent.com/37872928/186951902-a8f7e520-ce81-4d8c-8112-e3f7ad3c10fb.png)
Win 11, Ryzen 9 5950x
Works in Chrome 104, and justclueless/chromium-win64 [v107.0.5252.0-r0-AVX2](https://github.com/justclueless/chromium-win64/releases/tag/v107.0.5252.0-r0-AVX2)
I can provide more details if needed!

**Comment by Alex313031** [comment]
@SodaPortal What thorium version are you using. I can try to replicate in my Win 11 VM

**Comment by SodaPortal** [comment]
> @SodaPortal What thorium version are you using. I can try to replicate in my Win 11 VM

Version 107.0.5256.0

**Comment by SodaPortal** [comment]
Fixed in [M107.0.5271.0](https://github.com/Alex313031/Thorium-AVX2/releases/tag/M107.0.5271.0)
