### ISSUE TITLE
AVX2

### ISSUE THREAD

**Issue by trimechee** [Alex313031/Thorium-AVX2#33]
Hello, i would like to try Thorium-AVX2 but i dont't know if it is compatible, i have intel core i3 6006U asus laptop year 2017 model X541UK , is my processor compatilble with this Thorium version please ?

**Comment by Alex313031** [comment]
@gz83 @trimechee Yes, anything newer than 4th gen (processor number starting in 4, like i7 4790k, i5 4500, etc.) can use AVX2. On the AMD side, anything newer than 1st gen Ryzen will also have avx2

**Comment by trimechee** [comment]
@gz83 Great , thank you very much for your help, and sorry i didn't see your comment :(

@Alex313031, great thank you so much  :)
