### ISSUE TITLE
Move back in live youtube

### ISSUE THREAD

**Issue by trimechee** [Alex313031/Thorium-AVX2#39]
Hello i can't move back 10 second or more in this youtube live radio broadcast, i can go back with chromium   :  
https://www.youtube.com/watch?v=jMLB_2Z8bRU

**Comment by trimechee** [comment]
Yes  it worksfine  now  even when i go back 1 hour and more ! thank you :)  but when i wanted to change the video quality from 144p to 360p, it doesn't work anymore and there is no more video :(

**Comment by Alex313031** [comment]
@trimechee @gz83 Good. The video quality thing, I think is a youtube bug, not a thorium bug,

**Comment by trimechee** [comment]
If there is no bug with other browsers, that means this is a bug in Thorium, i don't have this bug in edge, frefox, chroumium  104......may be i will try justclueless version of chromium to be sure if it's a bug of Thorium or not .... I remind that the version of chromium 107 is not yet stable, it's a beta version so surely there are bugs

**Comment by Alex313031** [comment]
@trimechee It might be a bug in this version of thorium. I am uploading a new release now, you can try it and let me know.

**Comment by trimechee** [comment]
Amazing , thank you !
