### ISSUE TITLE
Catastrophe disaster : discrimination huge bug with heavy ads and crypto mining

### ISSUE THREAD

**Issue by trimechee** [Alex313031/Thorium-AVX2#41]
Hello, I thought chromium blocked by default natively heavy ads and crypto mining

https://blog.chromium.org/2020/05/resource-heavy-ads-in-chrome.html

  but I just discovered that chromium does not block heavy ads despite this option is implemented and integrated by default in chromium !  I tested with this site:

https://heavy-ads.glitch.me/

so regular classic version of chromium in woolyss site does not block heavy crypto ads and i test with microsoft edge browser and it blocks heavy ads, but Thorium browser does not block heavy ads it is an important option and i don't see more interest to use chromium if such important option does not work, please it will be great to activate this important option, thank you very much :)

**Comment by dabugen** [comment]
Get an adblocker like uBlock Origin - it´s free! Thorium is all about pureness without any interventions and most of us would like it to stay this way.

**Comment by trimechee** [comment]
Thank you for your precious advices :) i understand and i appreciate so much Thorium briwsers awesome features :)  so regular Thorium is more stable tahnt Thorium avx2 ? i use often youtube and Thorium avx2 has some problem with some youtube streams, I hesitate to install regular Thorium....

**Comment by trimechee** [comment]
chromium will migrate to manifest v3 and ublock origin developer said he won't develop ublock origin anymore if manifest v3 is applied, that's why native chromium ad blocker seems important  because it's the end, it's the end of classic ad blockers
