### ISSUE TITLE
Google AdSense dashboard doesn't load

### ISSUE THREAD

**Issue by SodaPortal** [Alex313031/Thorium-AVX2#43]
See #30 
Bug was first seen in [M107.0.5256.0](https://github.com/Alex313031/Thorium-AVX2/releases/tag/M107.0.5256.0), was fixed in [M107.0.5271.0](https://github.com/Alex313031/Thorium-AVX2/releases/tag/M107.0.5271.0).

The bug is back as of [M108.0.5314.0](https://github.com/Alex313031/Thorium-AVX2/releases/tag/M108.0.5314.0)

**Comment by SodaPortal** [comment]
@gz83 This issue is NOT present on Thorium-Win 5314 or other regular versions of Chromium, only Thorium-AVX2 5314.

**Comment by Alex313031** [comment]
@SodaPortal @tomByrer See if latest release fixes issues.
