### ISSUE TITLE
GitHub settings page sidebar doesn't navigate

### ISSUE THREAD

**Issue by SodaPortal** [Alex313031/Thorium-AVX2#44]
See original issue #31 
Bug was first seen in [M107.0.5256.0](https://github.com/Alex313031/Thorium-AVX2/releases/tag/M107.0.5256.0), was fixed in [M107.0.5271.0](https://github.com/Alex313031/Thorium-AVX2/releases/tag/M107.0.5271.0).

The bug is back as of [M108.0.5314.0](https://github.com/Alex313031/Thorium-AVX2/releases/tag/M108.0.5314.0)

**Comment by SodaPortal** [comment]
@gz83 This issue is NOT present on Thorium-Win 5314 or other regular versions of Chromium, only Thorium-AVX2 5314.

**Comment by Delphox** [comment]
I was just about to make an issue about this as well. I also faced problems on Discord (gives the "Well this is awkward" error page after using it for a few seconds), and Youtube Studio (the page contents show for a split second then immediately disappears into a blank page).

I can also confirm this issue happens on [107.0.5256.0](https://github.com/Alex313031/Thorium-AVX2/releases/tag/M107.0.5256.0), but NOT on [107.0.5271.0](https://github.com/Alex313031/Thorium-AVX2/releases/tag/M107.0.5271.0), which is the version I'm currently using, but unfortunately returned in [108.0.5314.0](https://github.com/Alex313031/Thorium-AVX2/releases/tag/M108.0.5314.0). I can also confirm it doesn't happen in the regular AVX releases of Thoriun-Win.

**Comment by Alex313031** [comment]
@Delphox @SodaPortal @tomByrer See if latest release fixes issues.

**Comment by Delphox** [comment]
@Alex313031 nope still happens. :(

**Comment by Delphox** [comment]
Issue still present in release from an hour ago :(

**Comment by Delphox** [comment]
> > Issue still present in release from an hour ago :(
> 
> @Delphox Does the latest released version still have this problem?

The one from this repo yes. Still loads a blank screen on Youtube Studio. Regular AVX version from Thorium-Win is fine.

**Comment by Delphox** [comment]
M110 seems to fix everything! YT studio loads and I've been using Discord Web for hours with no crash so far.

Small observation, the .bat launcher from the AVX2 zip release is still the old one without the new disable encryption and machine id arguments. However using the bat from regular Thorium-Win version works fine.

**Comment by Alex313031** [comment]
@Delphox Yeah, I mentioned in the release notes that everything should be fixed in M110. We finally found out the issue. We were using /fp:fast (floating point contraction = fast) during compilation, to make it faster. However, it looks like this causes bugs on windows (on linux it doesn't), and is most likely causing very small rounding errors in math routines used when rendering web pages, causing random and small breakages across sites.

**Comment by Alex313031** [comment]
@
