### ISSUE TITLE
The AVX2 version can not play youtube videos

### ISSUE THREAD

**Issue by CCCAUCHY** [Alex313031/Thorium-AVX2#45]
The AVX2 version can not play 480P or higher quality youtube videos but the [Win](https://github.com/Alex313031/Thorium-Win) version can

**Comment by CCCAUCHY** [comment]
> > The AVX2 version can not play 480P or higher quality youtube videos but the [Win](https://github.com/Alex313031/Thorium-Win) version can
> 
> @CCCAUCHY Hi, can you provide the URL of the video where the problem occurs so we can test t?

Every vidoes I clicked such as this [one](https://youtu.be/g0yd4n0OPeg), and zhihu.com can not work.

**Comment by Alex313031** [comment]
@CCCAUCHY See if latest release fixes issues.

**Comment by CCCAUCHY** [comment]
> @CCCAUCHY See if latest release fixes issues.

No, it did not fix.

**Comment by magoowa** [comment]
I sadly have to report same problem as well.

Running on i9-12900K (@5GHz, E-cores disabled), 128GB RAM, M.2 SSD, Win 11 Pro (build 22000.1098)

The AVX1 version is solid though and performance difference is very noticeable when comparing to Hibbiki Chromium. Thanks for your hard work!

**Comment by CCCAUCHY** [comment]
> @CCCAUCHY @magoowa
> 
> Please check if the new version solves the problem you encountered

Solved

**Comment by brian6932** [comment]
Can you close it then?

**Comment by magoowa** [comment]
Thank you @Alex313031, @gz83, @CCCAUCHY - I got the latest 111.0.5563.111 running for a while now, and no issues yet! Marvellous job on fixing this! 🥇
