### ISSUE TITLE
live login not working

### ISSUE THREAD

**Issue by mmyjona** [Alex313031/Thorium-AVX2#46]
But the Thorium for win version works well

**Comment by fastcat001** [comment]
@mmyjona do you mean outlook live mail login does not work?

**Comment by fastcat001** [comment]
@gz83 what are some recent issues?

**Comment by fastcat001** [comment]
@gz83 why could this be happening? Because Thorium is based on Dev build of chromium instead of Stable one?

**Comment by mmyjona** [comment]
https://login.live.com/

**Comment by mmyjona** [comment]
![image](https://user-images.githubusercontent.com/1235078/195749145-ab098f40-bf76-44c1-acd2-3914ee407985.png)
no, I use the portable zip

**Comment by Alex313031** [comment]
@mmyjona See if latest release fixes issue

**Comment by mmyjona** [comment]
No, the problem persists. BTW my CPUis amd 6800H.

**Comment by mmyjona** [comment]
it works now
