### ISSUE TITLE
Difference between Thorium and Chrome/Brave

### ISSUE THREAD

**Issue by ghost** [Alex313031/Thorium-AVX2#47]
@Alex313031 I checked your [performance comparison page](https://thorium.rocks/performance) and I see that Thorium performs better than Chrome and Brave.

Thorium supports sync and updates extensions, the same as Chrome and Brave.

I'm genuinely interested, why should anyone use Thorium over Chrome and Brave?
Because it's based on newer chromium builds?
But as Thorium is based on dev builds, does not only monthly updates of dev build hold security risks? Or am I mistaken?

I checked your [patches page](https://github.com/Alex313031/Thorium/blob/main/infra/PATCHES.md), but I could not understand most of the things, because I'm not a developer. i'm trying to determine why Thorium over Chrome and Brave (especially when brave has built-in blocker.

**Comment by Alex313031** [comment]
@ghost Newer chromium builds, and an amalgamation of patches from various sources. It has patches I made myself, patches from @robrich99, brave, ungoogled chromium, vanadium, ubuntu, iridium. The main thing, and a large focus of this fork is performance. I made two pages specifically about this on thorium's site > https://thorium.rocks/performance and https://thorium.rocks/optimizations
