### ISSUE TITLE
 Coinbase Wallet extension crashing

### ISSUE THREAD

**Issue by skver0** [Alex313031/Thorium-AVX2#49]
Seems to be crashing every single time, sometimes showing the page crashed screen with the message saying Out of memory.
Version 109.0.5362.0 (Official Build) (64-bit), Windows 10 64bit Home, 8gb ram

**Comment by skver0** [comment]
Thanks but I’m intrested in avx2 builds of chrome in general. I’ll wait till it gets fixed then.

**Comment by skver0** [comment]
Well I can't even run the latest build, using the mini installer.
![image](https://user-images.githubusercontent.com/32797351/227139011-c75228f1-39df-46ca-b41f-daa27495121b.png)

**Comment by Alex313031** [comment]
@skver0 @gz83 Yeah you must not be doing something right. Thorium has thorium.exe not chrome.exe.
