### ISSUE TITLE
Crashes in M101.0.4921.0 and M102.0.4952.0 

### ISSUE THREAD

**Issue by dabugen** [Alex313031/Thorium-AVX2#5]
Hi Alex,

first off, thanks for your efforts to build these AVX2 releases, I really appreciate it!

Both builds, M101.0.4921.0 and M102.0.4952.0 (fresh profiles used by completely deleting the profile directory before *each* test), are having steady crashes for me if running my Javascript based number-crunching app https://eas.forexsb.com/ It regularly crashes the tab with the infamous "Aww Snap. Status access violation". Using the "--disable-features=RendererCodeIntegrity" command line option doesn´t help with this either. Also, if going to Settings -> Search settings and typing something into the search field, Thorium closes instantly, there is also no entry in the event viewer that would show which kind of crash happened. These random closes also sometimes "just happen" while using Thorium for surfing.

Once using M100.0.4865.0, everything is fine and works flawlessly for days of number crunching. Also the Search settings doesn´t crash at all.

It would be great if you could address the issues. Thanks so much.

**Comment by gz83** [comment]
> Hi Alex,
> 
> first off, thanks for your efforts to build these AVX2 releases, I really appreciate it!
> 
> Both builds, M101.0.4921.0 and M102.0.4952.0 (fresh profiles used by completely deleting the profile directory before _each_ test), are having steady crashes for me if running my Javascript based number-crunching app https://eas.forexsb.com/ It regularly crashes the tab with the infamous "Aww Snap. Status access violation". Using the "--disable-features=RendererCodeIntegrity" command line option doesn´t help with this either. Also, if going to Settings -> Search settings and typing something into the search field, Thorium closes instantly, there is also no entry in the event viewer that would show which kind of crash happened. These random closes also sometimes "just happen" while using Thorium for surfing.
> 
> Once using M100.0.4865.0, everything is fine and works flawlessly for days of number crunching. Also the Search settings doesn´t crash at all.
> 
> It would be great if you could address the issues. Thanks so much.

Have you tried opening in win7 or win8 compatibility mode?

**Comment by dabugen** [comment]
I´ll try, but I think that compatibility mode will slow down the number crunching, which ain´t a good idea.

**Comment by Alex313031** [comment]
@dabugen Compatibility mode will not slow Thorium down, I tested it.

**Comment by dabugen** [comment]
The crashes persist in compatibility mode. Just going to settings and typing into the "Search settings" field crashes it already. M100.0.4865.0 is just fine, everything works perfectly there.

**Comment by Alex313031** [comment]
@dabugen What win version are you using. I'll be making a new release and I will test it in a VM with your windows version.

**Comment by dabugen** [comment]
Version 10.0.19044.1526

**Comment by Alex313031** [comment]
@dabugen Try latest release

**Comment by Lehner82** [comment]
Im pretty sure using compatibility mode disables video acceleration so that's really annoying right now

**Comment by dabugen** [comment]
@Alex313031 Thanks for the new build, but the same issue exists. Going to "Setting" -> "Search settings" and typing something into the search field, Thorium closes instantly. M100.0.4865.0 works flawlessly with that.

**Comment by Alex313031** [comment]
@Lehner82 It doesnt disable video acceleration in my testing? Can you confirm by going to chrome://gpu and posting screenshot?
@dabugen @gz83 I can confirm the search settings crashing issue. I'm looking into it.

**Comment by gz83** [comment]
> @Lehner82 It doesnt disable video acceleration in my testing? Can you confirm by going to chrome://gpu and posting screenshot? @dabugen @gz83 I can confirm the search settings crashing issue. I'm looking into it.

Thank you very much for your work, these problems seem to appear on the canary version as well. Don't know when upstream will be able to resolve it.

**Comment by dabugen** [comment]
Thanks for the efforts! Then we´ll have to wait until the fix the issue ;-)
