### ISSUE TITLE
Something wrong when viewing CNBC pages

### ISSUE THREAD

**Issue by Moe23333** [Alex313031/Thorium-AVX2#52]
Thorium Version: Thorium for Windows with AVX2 [109.0.5362.0](https://github.com/Alex313031/Thorium-AVX2/releases/tag/M109.0.5362.0)
System: Windows 11 Pro for Workstations [22623.870](https://blogs.windows.com/windows-insider/2022/10/20/announcing-windows-11-insider-preview-build-22621-870-and-22623-870)
CPU: Intel Core i5-12500H 2.50 GHz
GPU 0: Intel Iris Xe Graphics
GPU 1: NVIDIA GeForce RTX 2050
RAM: 16 GiB
Pages that have the problem: any CNBC pages, such as https://www.cnbc.com/2022/05/14/elon-musk-has-wrong-approach-to-count-fakes-spam-on-twitter-experts.html

As title and the picture below

I've tested to turn off all the extensions, there is still the problem; I've tested the latest version of Chromium (downloaded on https://download-chromium.appspot.com), it's no problem on Chromium.

![image](https://user-images.githubusercontent.com/35591595/198903190-727ac77a-4762-4471-896d-e3a2107dce84.png)

**Comment by Alex313031** [comment]
@Moe23333 Yeah latest version should fix this and alot of other problems with the avx2 version.
