### ISSUE TITLE
Youtube video resets or instantly ends upon clicking on progress bar or timestamp

### ISSUE THREAD

**Issue by Skalt711** [Alex313031/Thorium-AVX2#55]
What title says. Interestingly, devtools in Youtube complain that the maximum call stack size is exceeded. I can't provide a log rn because I don't want to suffer through the hell again.

**Comment by Skalt711** [comment]
I can't replicate the maximum call stack size message anymore, but the issue in the title remains. I confirmed that extensions don't affect the issue and it only appears in Thorium AVX2 for Windows on the 16th release M109 from Releases.

**Comment by Skalt711** [comment]
I can replicate the issue the most consistently on this video: https://www.youtube.com/watch?v=RDKWxMD5yDA

**Comment by lemon07r** [comment]
Having the same issue!
Happens consistently on this video https://www.youtube.com/watch?v=CpDYaYESJIc

**Comment by Alex313031** [comment]
@lemon07r @Skalt711 Should be fixed with the latest release.
