### ISSUE TITLE
AVX2 Build getting stuck on "Checking if the site connection is secure" on some sites

### ISSUE THREAD

**Issue by lemon07r** [Alex313031/Thorium-AVX2#57]
AVX2 Build (not sure if other builds are having the issue) is getting stuck on "Checking if the site connection is secure" on some sites. Example site: https://bobistheoilguy.com/forums/threads/is-liqui-moly-good-oil.256191/

**Comment by lemon07r** [comment]
Here is another: https://www.amsoil.ca/performance-tests/

**Comment by G2G2G2G** [comment]
browser benchmarks on some benchmarking sites are broken too, seems related to this from the network logs in dev console.

**Comment by Alex313031** [comment]
@lemon07r @G2G2G2G This issue should now be resolved with the M110 release.
