### ISSUE TITLE
SSE4 Thorium Release for people without AVX CPU's

### ISSUE THREAD

**Issue by vjrmy** [Alex313031/Thorium-AVX2#7]
Hi @Alex313031 , Is there an installation guide or Wiki for Thorium? because i little confused about installation.

i just downloaded from [Thorium-Win/releases](https://github.com/Alex313031/Thorium-Win/releases) and from [Thorium-AVX2/releases](https://github.com/Alex313031/Thorium-AVX2/releases) but when i open the file, it doesn't show anything.

and i want to ask what's the difference of zip file and mini installer exe file in [Thorium-AVX2/releases](https://github.com/Alex313031/Thorium-AVX2/releases) ?

btw, in [Thorium-Win/releases](https://github.com/Alex313031/Thorium-Win/releases), there are 2 files namely `.zip.exe` and `.exe.zip` make me confused too

**Comment by Alex313031** [comment]
@vjrmy The .exe is an installer, just double click and it will install Thorium silently and then open a new Thorium window. The .zip is a portable .zip so that you can run it on your system without installing. There is a README inside describing usage.

Therefore, there are two files, one with .exe and one with .zip extension. If your browser is downloading them as .exe.zip and .zip.exe, then I would say its a problem with your current browser and to try downloading them in a different browser.

**Comment by vjrmy** [comment]
it turns out that my laptop processor does not support avx or avx2 that's why thorium is not installed. my processor is intel celeron n3350

I will be happy if you release a version for my old processor. Thank you

**Comment by Alex313031** [comment]
@vjrmy A couple of people have asked for this too. I'll make an SSE4 version for yall and post it in thorium-special.

**Comment by vjrmy** [comment]
I'll be waiting for that

**Comment by Alex313031** [comment]
@vjrmy

**Comment by vjrmy** [comment]
I found it. thanks my friend for telling me

**Comment by vjrmy** [comment]
but the package is debian `.deb` which can't be installed on windows 10. Is there a package that is `.exe`?

**Comment by gz83** [comment]
> but the package is debian `.deb` which can't be installed on windows 10. Is there a package that in `.exe`?

@vjrmy Thorium has installation packages in `deb` and `exe` format, as well as portable version for windows. The installation package can be downloaded from the following page.

AVX version https://github.com/Alex313031/Thorium/releases/tag/M103.0.5036.0

AVX2 version
https://github.com/Alex313031/Thorium-AVX2/releases/tag/M103.0.5045.0

**Comment by Alex313031** [comment]
@vjrmy OMFG I'm dumb. I just realized this issue was in Thorium-AVX2 so obviously you are looking for a SSE4 windows release. I will make one soon for you.

**Comment by Alex313031** [comment]
@vjrmy Hey, @gz83 Is making an sse4 only release as well as an ARM release for windows.

**Comment by Alex313031** [comment]
@vjrmy Ok here you go > https://github.com/Alex313031/Thorium-Special/releases/tag/M104.0.5091.0
