### ISSUE TITLE
Add Per Tab Webcam , mic , output device so that i can have a different one per tab or at least have different Webcam , mic , output device per user profile open so that i can have 2 different windows open with different mic and output device and webcam

### ISSUE THREAD

**Issue by Pickymarker** [Alex313031/Thorium-AVX2#74]
Add Per Tab Webcam , mic , output device so that i can have a different one per tab or at least have different Webcam , mic , output device per user profile open so that i can have 2 different windows open with different mic and output device and webcam

**Comment by Alex313031** [comment]
@Pickymarker This is not possible without a SIGNIFIGANT rewrite of the Chromium audio subsystem, including having to change things for each platform. It is not something I would know how to do, and would take alot of rebasing even if I knew how. Im sorry.
