### ISSUE TITLE
How to activate auto updates?

### ISSUE THREAD

**Issue by Veriiix** [Alex313031/Thorium-AVX2#75]
title

**Comment by Veriiix** [comment]
so i can just install the updates on top of the last version?

**Comment by Veriiix** [comment]
> make a backup of user data
where can i find the required user data ?

**Comment by Alex313031** [comment]
@Veriiix @gz83 It is not usually required to make a backup of the user data dir. Uninstalling is best, but I have found that installing new thorium over old install usually works okay.
