### ISSUE TITLE
Did you forget new version for AVX2?

### ISSUE THREAD

**Issue by CCCAUCHY** [Alex313031/Thorium-AVX2#82]

**Comment by gz83** [comment]
The AVX2 version has been compiled, please wait patiently for the new version to be released @CCCAUCHY

**Comment by ms178** [comment]
@gz83 Is this also true for the Linux build as discussed in #80 ?

**Comment by gz83** [comment]
@ms178 

I'm not in charge of building the linux version, need Alex to explain what's going on with the linux-avx2 version.

**Comment by Alex313031** [comment]
@CCCAUCHY @
