### ISSUE TITLE
Tab Scrolling issue.

### ISSUE THREAD

**Issue by HongYue1** [Alex313031/Thorium-AVX2#86]
**System Details**
 - OS: Windows 11 22621.1702
 - Thorium Version 22621.1702

**Problem**
When dragging a tab to the right, just after my mouse passes the new tab button the browser or to the leftmost part of the screen the browser and all of it's instances suddenly closes.

**Comment by gz83** [comment]
Are there experimental flags turned on?

@HongYue1

**Comment by HongYue1** [comment]
> Are there experimental flags turned on?
> 
> @HongYue1

No I didn't touch anything, I will try reinstalling it to see if it will fix it.

**Comment by HongYue1** [comment]
I found the problem, changing tab scrolling in the lab from default to enabled caused this.

**Comment by HongYue1** [comment]
Instead of opening a new issue since they are both related.

If tab scrolling is set to default or disabled, this gab is not aligned right:

![image](https://github.com/Alex313031/Thorium-AVX2/assets/87040288/3ecf14ac-50e6-4ffc-9949-937ed9aeab74)



if it's set to enable, this problem is fixed, BUT I have the above issue which crashes the browser:

![image](https://github.com/Alex313031/Thorium-AVX2/assets/87040288/ab1c9f68-a3d2-4448-9609-22553e5a8286)


 It has nothing to do with the themes, since I have tried different themes and even the default has it.
