### ISSUE TITLE
Pinned tabs becoming inaccessible

### ISSUE THREAD

**Issue by lemon07r** [Alex313031/Thorium-AVX2#87]
**System Details**
 - OS: Windows 11
 - Thorium Version: 112.0.5615.166

**Problem**
Pinned tabs randomly disappear, leaving empty space where they should be and become unclickable. Issue is only resolved by closing the browser and opening it again.

**Screenshots**
<img width="114" alt="image" src="https://github.com/Alex313031/Thorium-AVX2/assets/12001338/e2afcbfa-a258-4e0f-a3b0-f4ffd4c33276">

**Additional Notes**
It seems to be completely random, I haven't figured out the trigger. Sometimes it happens right away, sometimes it only happens after a while. My pinned tabs consist of youtube and discord. This effects all pinned tabs at the same time. 

Edit: Changing tab scrolling to disabled from default in thorium experiments seems to have fixed this issue.

**Comment by gz83** [comment]
This issue may be caused by the double click close tab patch, I will discuss this issue with Alex

@lemon07r

**Comment by lemon07r** [comment]
Here are screenshots as promised.
<img width="114" alt="image" src="https://github.com/Alex313031/Thorium-AVX2/assets/12001338/a645e9d4-8085-4958-bef8-b20a114514b4">
Doesnt come back until closing the browser.

**Comment by lemon07r** [comment]
Changing tab scrolling to disabled from default in thorium experiments seems to have fixed this issue.
