### ISSUE TITLE
Found that some websites cannot be opened

### ISSUE THREAD

**Issue by mx4994** [Alex313031/Thorium-AVX2#88]
https://ip.skk.moe/ For example, this website does not open.
I tried disabling extensions and incognito mode, but they couldn't be opened, but chrome can be opened normally.

**Comment by gz83** [comment]
The problem has been reproduced locally, try the latest release of AVX version of Thorium browser, see if you can open the above website

**Comment by gz83** [comment]
Please follow the steps below to continue the troubleshooting：
1、Try in incognito mode
2、Uninstall and install the latest version of Thorium browser, and reopen the website that cannot be accessed properly

@mx4994
