### ISSUE TITLE
A small problem with the portable version

### ISSUE THREAD

**Issue by mx4994** [Alex313031/Thorium-AVX2#93]
When I use THORIUM.BAT to create USER_DATA in the current directory and set a shortcut on the taskbar, synchronize my data, and set it as the default application,

If I do not open Thorium for this shortcut, when I click the link elsewhere, the link will be opened by the default browser. At this time, Thorium will generate a new USER_DATA under the system user AppData, a blank browser, None of the things I set.

So since it is a portable version, why can't it be like other software, where the user data is created wherever it is decompressed, instead of creating a shortcut.

**Comment by Alex313031** [comment]
@mx4994 Can you try setting the actual .bat as the default application, instead of thorium.exe

**Comment by Alex313031** [comment]
@mx4994 Setting a browser as a default handler for links happens in the registry, and only properly works when the browser is installed. You are right, you cant set a .bat as a default program. In your use case, it sounds like installing it would be the best thing. Why are you using the portable version if you are going to set it as your default browser anyway?
