### ISSUE TITLE
Browser Crash on "manage profiles".

### ISSUE THREAD

**Issue by fuu1** [Alex313031/Thorium-AVX2#95]
**System Details**
 - OS: Windows 10 22h2 Build 19045.3086
 - Thorium Version: 114.0.5735.134 (AVX2)
 - CPU: i5 7200u

**Problem**
The Browser crashes when trying to open the profile management page.

**Screenshots/Media**

https://github.com/Alex313031/Thorium-AVX2/assets/25006752/40d17316-f275-4c2a-ab5c-270a7dde4f66

**Additional Notes**
The stability of the browser was perfectly fine else. I don't use the feature, so it isn't a big concern.

**Comment by MrPokeboy8** [comment]
This issue also causes Thorium to not open when there are multiple profiles; only Private windows could open. Viewing Task Manager, Thorium would attempt to run and self-close soon afterwards.
Affects both AVX2 and Win 114 versions.

**Comment by gz83** [comment]
We were able to reproduce the issue in local tests and will do more troubleshooting

@fuu1 @MrPokeboy8

**Comment by Alex313031** [comment]
@gz83 Yup can confirm.

What about the 113 version?

**Comment by gz83** [comment]
I'll be troubleshooting this in a subsequent release of the new version

@Alex313031

**Comment by fortunewalla** [comment]
Same issue. It is fine when opening Private Window & Guest Mode but crashes on Add Profile.

VERSION: `114.0.5735.134`

OS: Windows 10 22h2


E:\thoriumavx2>START "" "E:\thoriumavx2\BIN\thorium.exe" --user-data-dir="E:\thoriumavx2\\USER_DATA" --allow-outdated-plugins --disable-logging --disable-breakpad --enable-experimental-web-platform-features --new-canvas-2d-api --disable-encryption --disable-machine-id --gpu --gpu-launcher --in-process-gpu --ignore-gpu-blacklist --ignore-gpu-blocklist --enable-unsafe-webgpu --use-webgpu-adapter=d3d11

**Comment by gz83** [comment]
Improve visibility of this issue in my mailbox: This issue is caught in both Linux and Windows versions

**Comment by Alex313031** [comment]
@gz83 @fortunewalla @fuu1 @MrPokeboy8 @midzer This bug was present on all platforms. I have fixed it in the M115 release. Wait for us to release builds and it should be fixed now.

**Comment by fortunewalla** [comment]
I created a few profiles, it did not crash when switching profiles.
I also enabled the autoplay flag & tried switching profiles & creating profiles, it did not crash.

Thanks for doing this. 👏🏼

**Comment by luisenriquereyes** [comment]
> @gz83 @fortunewalla @fuu1 @MrPokeboy8 @midzer This bug was present on all platforms. I have fixed it in the M115 release. Wait for us to release builds and it should be fixed now.
> 
> It was very strange, and related to me enabling AutoPlay toggle in settings. Normally its disabled. In any case, you can still control autoplay behavior with the Thorium specific flag `chrome://flags/#autoplay-policy`

Enabling AutoPlay toggle in settings fixed for me running AVX2 version 121.0.6167.204 (Official Build) (64-bit).  Thank you

**Comment by pathbouncer** [comment]
AVX2 build on ubuntu 22.04.04 fresh install was crashing when trying to add another profile. i changed the setting from default to document and the crashing is resolved.
